"""init_db

Revision ID: be75eebb0123
Revises: 
Create Date: 2025-11-08 17:24:29.025571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be75eebb0123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('nomeLocal', sa.String(length=255), nullable=False, comment='Nome do local'),
    sa.Column('logradouro', sa.String(length=255), nullable=False, comment='Logradouro do endereço'),
    sa.Column('numero', sa.String(length=20), nullable=False, comment='Número do endereço'),
    sa.Column('complemento', sa.String(length=100), nullable=True, comment='Complemento do endereço'),
    sa.Column('bairro', sa.String(length=100), nullable=False, comment='Bairro do endereço'),
    sa.Column('cep', sa.String(length=10), nullable=False, comment='CEP do endereço'),
    sa.Column('cidade', sa.String(length=100), nullable=False, comment='Cidade do endereço'),
    sa.Column('estado', sa.String(length=2), nullable=False, comment='Estado do endereço'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Latitude geográfica'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Longitude geográfica'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('funcionalidades',
    sa.Column('chave', sa.Integer(), autoincrement=True, nullable=False, comment='Chave de acesso autoincrementada'),
    sa.Column('nome', sa.String(length=100), nullable=False, comment="Nome amigável da funcionalidades (ex: 'Excluir Cliente')"),
    sa.Column('escopo', sa.String(length=50), nullable=False, comment="Identificador único no formato 'recurso:ação' (ex: 'client:delete')"),
    sa.Column('caminho', sa.String(length=255), nullable=False, comment="Endpoint da API (ex: '/api/client/{id}')"),
    sa.Column('metodo', sa.String(length=10), nullable=False, comment='Método HTTP (GET, POST, PUT, DELETE, etc)'),
    sa.Column('descricao', sa.String(length=500), nullable=True, comment='Descrição detalhada do propósito da funcionalidades'),
    sa.Column('categoria', sa.String(length=50), nullable=True, comment="Grupo funcional (ex: 'CRM', 'Financeiro', 'Relatórios')"),
    sa.Column('sensivel', sa.Boolean(), nullable=True, comment='Indica se é uma operação crítica/cuidado extra necessário'),
    sa.Column('versao', sa.Integer(), nullable=True, comment='Versão da funcionalidades para controle de evolução'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.PrimaryKeyConstraint('chave', 'id'),
    sa.UniqueConstraint('escopo'),
    sa.UniqueConstraint('id')
    )
    op.create_table('papeis',
    sa.Column('nome', sa.String(length=45), nullable=False, comment="Nome identificador único do papeis (ex: 'Admin', 'Gerente')"),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Indica se o papeis está ativo e disponível para atribuição'),
    sa.Column('descricao', sa.String(length=250), nullable=True, comment='Descrição detalhada das permissões e responsabilidades do papeis'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('vacinas',
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome da vacina'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('campanhas',
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome da campanha'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status da campanha'),
    sa.Column('doses_aplicadas', sa.Integer(), nullable=False, comment='Quantidade de doses aplicadas na campanha'),
    sa.Column('data_inicio', sa.Date(), nullable=False, comment='Data de início da campanha'),
    sa.Column('data_fim', sa.Date(), nullable=False, comment='Data de fim da campanha'),
    sa.Column('publico_alvo', sa.String(length=255), nullable=False, comment='Público-alvo da campanha'),
    sa.Column('meta_vacinacao', sa.Integer(), nullable=False, comment='Meta de vacinação da campanha'),
    sa.Column('descricao', sa.Text(), nullable=False, comment='Descrição da campanha'),
    sa.Column('horario_funcionamento', sa.String(length=100), nullable=False, comment='Horário de funcionamento da campanha'),
    sa.Column('endereco_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando o Endereço'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('papeis_funcionalidades',
    sa.Column('papel_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando o ID do Papeis'),
    sa.Column('funcionalidade_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['funcionalidade_id'], ['funcionalidades.id'], ),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.PrimaryKeyConstraint('papel_id', 'funcionalidade_id', 'id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('unidades',
    sa.Column('endereco_id', sa.UUID(), nullable=True, comment='Chave estrangeira referenciando o Endereço'),
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome da unidade'),
    sa.Column('nome_usuario_responsavel', sa.String(length=255), nullable=True, comment='Nome do usuário responsável pela unidade'),
    sa.Column('tipo', sa.String(length=100), nullable=True, comment='Tipo da unidade'),
    sa.Column('codigo_cnes', sa.String(length=50), nullable=False, comment='Código CNES da unidade'),
    sa.Column('contato', sa.String(length=50), nullable=True, comment='Contato da unidade'),
    sa.Column('email_unidade', sa.String(length=255), nullable=True, comment='E-mail da unidade'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Status da unidade'),
    sa.Column('capacidade_pacientes', sa.String(length=100), nullable=True, comment='Capacidade de pacientes da unidade'),
    sa.Column('horario_funcionamento', sa.String(length=100), nullable=True, comment='Horário de funcionamento da unidade'),
    sa.Column('informacoes_servico', sa.Text(), nullable=True, comment='Informações sobre os serviços da unidade'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cnes'),
    sa.UniqueConstraint('id')
    )
    op.create_table('agendas',
    sa.Column('unidade_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Unidade'),
    sa.Column('titulo', sa.String(length=255), nullable=False, comment='Título da agenda'),
    sa.Column('capacidade_diaria', sa.Integer(), nullable=False, comment='Capacidade diária de agendamentos'),
    sa.Column('hora_inicio', sa.Integer(), nullable=False, comment='Hora de início do atendimento'),
    sa.Column('hora_fim', sa.Integer(), nullable=False, comment='Hora de fim do atendimento'),
    sa.Column('data_inicio', sa.Date(), nullable=False, comment='Data de início da agenda'),
    sa.Column('data_fim', sa.Date(), nullable=False, comment='Data de fim da agenda'),
    sa.Column('dias_semana', sa.String(length=50), nullable=False, comment='Dias da semana em que a agenda está ativa'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('campanhas_unidades',
    sa.Column('campanha_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Campanha'),
    sa.Column('unidade_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Unidade'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('campanha_id', 'unidade_id', 'id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('lotes',
    sa.Column('vacina_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Vacina'),
    sa.Column('fabricante', sa.String(length=255), nullable=False, comment='Fabricante do lote'),
    sa.Column('quantidade_total', sa.Integer(), nullable=False, comment='Quantidade total de vacinas no lote'),
    sa.Column('validade_aberto', sa.Integer(), nullable=False, comment='Validade após abertura (em dias)'),
    sa.Column('validade_fechado', sa.DateTime(), nullable=False, comment='Validade do lote fechado'),
    sa.Column('lote_numero', sa.String(length=100), nullable=False, comment='Número do lote'),
    sa.Column('lote_quantidade_atual', sa.Integer(), nullable=True, comment='Quantidade atual de vacinas no lote'),
    sa.Column('lote_validade_fechado', sa.Date(), nullable=False, comment='Data de validade do lote fechado'),
    sa.Column('unidade_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Unidade'),
    sa.Column('local_refrigerador', sa.String(length=100), nullable=False, comment='Localização no refrigerador'),
    sa.Column('temperatura_vacina', sa.String(length=50), nullable=False, comment='Temperatura de armazenamento'),
    sa.Column('local_posicao', sa.String(length=100), nullable=False, comment='Posição no local de armazenamento'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='Resposável por abertura'),
    sa.Column('doses_utilizadas', sa.Integer(), nullable=True, comment='Quantidade de doses utilizadas'),
    sa.Column('data_abertura', sa.DateTime(), nullable=False, comment='Coluna de data de abertura das vacinas'),
    sa.Column('motivo_abertura', sa.String(length=250), nullable=True, comment='Relatar o motivo da abertura das vacinas'),
    sa.Column('data_descarte', sa.DateTime(), nullable=False, comment='Coluna de data de descarte das vacinas'),
    sa.Column('motivo_descarte', sa.String(length=250), nullable=True, comment='Relatar o motivo da descarte das vacinas'),
    sa.Column('codigo_barras', sa.String(length=255), nullable=True, comment='Código de barras do lote'),
    sa.Column('doses_por_frasco', sa.Integer(), nullable=True, comment='Quantidade de doses por frasco'),
    sa.Column('data_fabricacao', sa.DateTime(), nullable=True, comment='Data de fabricação do lote'),
    sa.Column('status', sa.String(length=255), nullable=False, comment='Fabricante do lote'),
    sa.Column('unidade_validade', sa.String(length=255), nullable=False, comment='Fabricante do lote'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['vacina_id'], ['vacinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('lote_numero')
    )
    op.create_table('usuarios',
    sa.Column('nome_usuario', sa.String(length=100), nullable=False, comment='Nome de usuário para login'),
    sa.Column('nome_completo', sa.String(length=255), nullable=False, comment='Nome completo do usuário'),
    sa.Column('telefone', sa.String(length=20), nullable=True, comment='Telefone do usuário'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='E-mail do usuário'),
    sa.Column('senha', sa.LargeBinary(), nullable=False, comment='Senha criptografada do usuário'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Indica se o usuário está ativo'),
    sa.Column('papel_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando o Papel'),
    sa.Column('unidade_id', sa.UUID(), nullable=True, comment='Chave estrangeira referenciando a Unidade'),
    sa.Column('cargo', sa.String(length=100), nullable=True, comment='Cargo do usuário'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.create_table('agendamentos',
    sa.Column('agenda_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Agenda'),
    sa.Column('vacina', sa.String(length=255), nullable=True, comment='Nome da vacina a ser aplicada'),
    sa.Column('tipo_identificacao_paciente', sa.String(length=50), nullable=False, comment='Tipo de identificação do paciente'),
    sa.Column('numero_identificacao_paciente', sa.String(length=100), nullable=False, comment='Número de identificação do paciente'),
    sa.Column('hora', sa.Time(), nullable=False, comment='Hora do agendamento'),
    sa.Column('data', sa.Date(), nullable=False, comment='Data do agendamento'),
    sa.Column('protocolo', sa.String(length=100), nullable=True, comment='Protocolo do agendamento'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Status do agendamento'),
    sa.Column('registro_data_hora_atendimento', sa.DateTime(), nullable=True, comment='Data e hora do atendimento registrado'),
    sa.Column('usuario_responsavel_id', sa.UUID(), nullable=True, comment='Chave estrangeira referenciando o Usuário Responsável'),
    sa.Column('usuario_responsavel_nome', sa.String(length=255), nullable=True, comment='Nome do usuário responsável pelo atendimento'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['usuario_responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('protocolo')
    )
    op.create_table('agendas_vacinas',
    sa.Column('vacina_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Vacina'),
    sa.Column('agenda_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando a Agenda'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['vacina_id'], ['vacinas.id'], ),
    sa.PrimaryKeyConstraint('vacina_id', 'agenda_id', 'id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('usuarios_funcionalidades',
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando o ID do Usuário'),
    sa.Column('funcionalidade_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando o ID da Funcionalidades'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['funcionalidade_id'], ['funcionalidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'funcionalidade_id', 'id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('vacinas_aplicadas',
    sa.Column('lote_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando o Lote'),
    sa.Column('agendamento_id', sa.UUID(), nullable=False, comment='Chave estrangeira referenciando o Agendamento'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUIDv4) da entidade'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora UTC da criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True, comment='Data e hora UTC da última atualização do registro (null se nunca foi atualizado)'),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacinas_aplicadas')
    op.drop_table('usuarios_funcionalidades')
    op.drop_table('agendas_vacinas')
    op.drop_table('agendamentos')
    op.drop_table('usuarios')
    op.drop_table('lotes')
    op.drop_table('campanhas_unidades')
    op.drop_table('agendas')
    op.drop_table('unidades')
    op.drop_table('papeis_funcionalidades')
    op.drop_table('campanhas')
    op.drop_table('vacinas')
    op.drop_table('papeis')
    op.drop_table('funcionalidades')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
